# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtQqR3gVUcBVy8c0ZwD0dCVIa07UYNXg
"""

#power of a number with x**n with time and space complexity as O(logn)
def power(x,n):
  if n==0:
    return 1
  smallpower=power(x,n//2)
  if n%2==0:
    return smallpower*smallpower
  else:
    return x*smallpower*smallpower
power(2,4)